[ADD] Product Detail View
wecode-bootcamp-korea/31-1st-kidsney-backend pull request #6
Opened 2022-04-04 11:37 UTC by kdh10806

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상세페이지 view 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 전체 상품 중에서 해당 product_id의 상품만 보여주는 상세페이지입니다.
2. 상세페이지에서 상품별 리뷰를 남길 수 있습니다. 리뷰확인/리뷰삭제 모두 가능합니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- delete method 사용을 처음해봐서 고민을 많이 해봤습니다.

<br />

## :: 기타 질문 및 특이 사항
- 상품하나당 유저는 하나의 리뷰를 남길 수 있도록 구현하는게 나을지 협의중입니다.

2022-04-05 08:30 UTC, jamessoun93 requested changes

2022-04-05 08:30 UTC, jamessoun93 commented on products/views.py
> +                'user'      : review.user.last_name + review.user.first_name + f'({review.user.email})',
이렇게 프론트엔드에서 보여줘야하는 형식을 그대로 맞춰서 보내준다면, 기획이 바뀌어서 해당 포맷이 바뀌게되면 이쪽에서 직접 수정을 해야하는 문제가 있습니다. 필요한 정보는 전부 보내주되 프론트엔드에서 유연하게 처리가 가능하도록 response 구조를 만들어주시는게 좋습니다. 

```python
'user': {
    'first_name': '승현',
    'last_name': '손',
    'email': 'james@gracefulrain.co'
}
```

2022-04-05 08:30 UTC, jamessoun93 commented on products/views.py
> +        product = Product.objects.get(id = product_id)
exception 처리 추가해주세요.

2022-04-05 08:30 UTC, jamessoun93 commented on products/views.py
> +        review = Review.objects.filter(id = review_id, product_id =product_id ,user = user)
QuerySet은 리스트의 형태를 띄기때문에 변수명을 복수형으로 지어주시고 `=` 앞뒤로 간격 통일해주세요.

2022-04-05 08:30 UTC, jamessoun93 commented on products/views.py
> +            return JsonResponse({'message' : 'INVALID_USER'}, status = 400)
해당 filter문에 대한 결과로 빈 쿼리셋이 리턴된다면 해당 조건에 맞는 리뷰들이 존재하지 않는다는 뜻인데 INVALID USER에 400이 알맞은 리스폰스일까요?

2022-04-05 09:25 UTC, kdh10806 commented
말씀해주신 부분 수정했습니다.

2022-04-06 01:39 UTC, jamessoun93 requested changes

2022-04-06 01:39 UTC, jamessoun93 commented on products/views.py
> +            return JsonResponse({'message' : 'REVIEW_NOT_EXIST'}, status = 401)
이 부분은 HTTP 상태코드 401과는 관련이 없어보이네요. 수정해주세요!

2022-04-06 01:40 UTC, jamessoun93 requested changes
HTTP 상태코드에 대한 공부가 필요해보이네요~
굉장히 중요한 부분이니 꼭 시간내서 공부해주세요.

2022-04-06 01:40 UTC, jamessoun93 commented on products/views.py
> +            return JsonResponse({'message' : 'CREATED'}, status=200)
```suggestion
            return JsonResponse({'message' : 'CREATED'}, status=201)
```

2022-04-06 03:12 UTC, kdh10806 commented
수정사항 올렸습니다. status code 관련해서 공부하겠습니다.

2022-04-06 05:07 UTC, jamessoun93 approved these changes

2022-04-06 05:07 UTC, merged